### ISSUE TITLE
the ERROR status

### ISSUE THREAD

**Issue by HeTian123abc** [center-for-threat-informed-defense/tram#123]
I run the project with docker, after submitting the report, the status is from QUIRED to ERROR, why?

**Comment by MarkDavidson** [comment]
@HeTian123abc 

The error output should be capture on STDOUT within the Docker container. There are two ways you can access the error log:
1. If you are running Docker desktop, you can use the UI to view the log (See screenshot below)
2. If you are running Docker via command line, you can use the docker logs command to retrieve the error: https://docs.docker.com/engine/reference/commandline/logs/

![image](https://user-images.githubusercontent.com/2951827/146057562-cf32bda1-683b-4fc2-b26c-d969bb330907.png)

Try that, and if you get stuck let me know.
Thank you.
-Mark

**Comment by HeTian123abc** [comment]
When running docker, there is a NLTK problem, but it does not affect the operation. I don't know whether it has affect.
![捕获1](https://user-images.githubusercontent.com/83320050/146124657-e8e1833a-5845-43c4-bfa8-c4e0f58431f6.PNG)
When uploading the report, the status is from QUEUED to ERROR.
![捕获2](https://user-images.githubusercontent.com/83320050/146124947-9205ea1e-f94a-4863-9659-103825c3b4ea.PNG)

**Comment by HeTian123abc** [comment]
![捕获3](https://user-images.githubusercontent.com/83320050/146174230-ccd0530a-560d-46d9-adf1-4ebf87c7509c.PNG)

**Comment by HeTian123abc** [comment]
resolved
