### ISSUE TITLE
Queued state problem

### ISSUE THREAD

**Issue by cho-jinyoung** [center-for-threat-informed-defense/tram#131]
After installing the docker, upload the file, and it no longer proceeds in the queued state.
How can I solve this problem?

**Comment by svniedner** [comment]
Having the same problem -- any idea how to fix it? (master-V1.1.1)

**Comment by emmanvg** [comment]
potential duplicate #114

**Comment by ghostpepper108** [comment]
I think I am facing the same problem when using docker-compose. After I submit the pdf, it perpetually stays in "Queued" status. Sometimes, after restarting the portal with docker-compose, it generates the report but not sure if it is completed its job.

**Comment by cho-jinyoung** [comment]
I still can't solve it. I have to restart to proceed. Is this the right way?

**Comment by ghostpepper108** [comment]
For me restart apparently generates the report

**Comment by ghostpepper108** [comment]
@emmanvg - Looks like the issue is still persisting ,that is uploading the pdf/word files gets stuck in the pipeline until the restarting docker-compose
