### ISSUE TITLE
Unable to add new attack object

### ISSUE THREAD

**Issue by Wojak394** [center-for-threat-informed-defense/tram#163]
Hi, I'm unable to add new object in "Attack Objects" panel in admin account with new name, stix id, attack id, attack url and matrix. 
It is allowed to write only stix type and attack type when I add new object. 
In my example I would like to add new technique "Stage Capabilities" with Id T1608 and it's sub-techniques, but it's not possible. I can only add new object with empty name and i don't want it of course :) .

**Comment by mehaase** [comment]
Hi @Wojak394, that's a good point. I'm not sure why those fields are not editable in the Django admin. I've created a PR to fix it. Can you check out that branch and give it a test? I want to make sure that this change doesn't cause a regression somewhere else. Thanks

**Comment by Wojak394** [comment]
Hi @mehaase thank you very much for your reply. It seems to be fine. I've made a test and it works. Thanks again, great job!
