### ISSUE TITLE
unable to upload a document

### ISSUE THREAD

**Issue by pshurie** [center-for-threat-informed-defense/tram#183]
below is my call along with the results: (returning 301 and not uploading new report)

curl -X POST -H 'Cookie: csrftoken=7o0DcuWyLp1doaDEgGtld5GWHFnPdOWeGqjSqeYWJWOVRK2ngm1JjbwAYlUnqEvs;sessionid=ds3gxtx2ecm6ovwuzinzm4ukytwmossj' -d '{"csrfmiddlewaretoken":"7o0DcuWyLp1doaDEgGtld5GWHFnPdOWeGqjSqeYWJWOVRK2ngm1JjbwAYlUnqEvs","name":"patTest","filename":"patText.html","type":"text/html","data":"<!DOCTYPE html><html><body>This is the content</body></html>"}' http://localhost:8000/upload -v

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /upload HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.79.1
> Accept: */*
> Cookie: csrftoken=7o0DcuWyLp1doaDEgGtld5GWHFnPdOWeGqjSqeYWJWOVRK2ngm1JjbwAYlUnqEvs;sessionid=ds3gxtx2ecm6ovwuzinzm4ukytwmossj
> Content-Length: 222
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.21.5
< Date: Fri, 09 Sep 2022 17:21:09 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Location: /upload/
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
< 
* Connection #0 to host localhost left intact

**Comment by mehaase** [comment]
Hi @pshurie based on the response it looks like its asking for an extra slash at the end of the URL, e.g. change `http://localhost:8000/upload` to `http://localhost:8000/upload/`.

**Comment by mehaase** [comment]
I'm testing this out locally and here a couple other notes:

1. The payload needs to be form-encoded, not JSON encoded.

2. The csrftoken and csrfmiddlewaretoken are two different things. To obtain the csrfmiddlewaretoken, you need to fetch the index page and parse the value out of this hidden form element:

<img width="919" alt="Screen Shot 2022-09-16 at 11 00 37 AM" src="https://user-images.githubusercontent.com/320904/190669930-55d2a164-52af-4ca1-bd6f-68c260799ea2.png">

Here's an example to demonstrate. Not recommending you do it this way in production, but it's good enough for testing:

```bash
bash-3.2$ csrftoken="34K0NeHfqvEE6Jaj6KYLyWlTMsC0Png7ngKkfeU8V09aBcdRENvlClLcpYgupuux"

bash-3.2$ sessionid="5cq69l6h56vle5wzw5l1msvbal67cbp5"

bash-3.2$ token=$(curl 'http://localhost:8000/' -s \
>   -H "Cookie:csrftoken=$csrftoken;sessionid=$sessionid" \
>   | grep csrfmiddlewaretoken \
>   | cut -d '"' -f 6)

bash-3.2$ curl 'http://localhost:8000/upload/' \
>   -H "Cookie:csrftoken=$csrftoken;sessionid=$sessionid" \
>   -F "csrfmiddlewaretoken=$token"\
>   -F "file=@my_report.txt"
{"message": "File saved for processing.", "job-id": 14, "doc-id": 14}
bash-3.2$
```

Note that I set two variables at the beginning just to make things easier to read. The third command downloads the main TRAM page, parses out the CSRF token from the form, and saves it into `$token`. Finally, the fourth command does a form post with the CSRF token obtained in step 3 and reads in a file called `my_report.txt`.

Let me know if this works for you.

**Comment by pshurie** [comment]
I'll give that a go.

I have one more question for you:

   1. Another question I have for you has to do with the database. is the
   data stored in a database that is clustered?The reason why I ask is that we
   are setting up tram in a kubernetes cluster and wondering if I should use a
   deployment or a stateful set. If there is no cluster I will just use a
   deployment with a pod replica set all pointing to the same volume, but if
   the database is used in a cluster I will need to use a stateful set.

I've been looking at the tram code and see you are using sqlite3 with
django so it looks like there is no cluster so I think I want to set it up
as a deployment where each pod is accessing the same volume like so:


                  tram pod1 --->
nginx --> 1 volume claim  ----> volumes (one for /tram/data and the other
for /tram/src/tram/staticfiles)
                 tram pod2--->

Does that seem reasonable where all tram instances point to the same
volume? (sorry I don't have paint)
thanks for your help Mark. I really appreciate it!

**Comment by mehaase** [comment]
The database is a SQLite file. You are correct in thinking about a volume to share the data between pods, however I don't think it's going to work well in practice. SQLite is not designed to scale up to a lot of concurrent users and requires an exclusive lock anytime a change is written to the database. I'm not sure if the locking mechanism will work in the k8s volume scenario, and even if it does, I expect the resulting performance to be disappointing. At best, concurrent access would be slow, and at worst users would see strange errors or even data corruption. (This is just my best guess--I haven't actually tested out Django+SQLite+K8s in the configuration above.)
