### ISSUE TITLE
Missing file "classes.txt"

### ISSUE THREAD

**Issue by kirankc** [center-for-threat-informed-defense/tram#195]
Anyone else having this issue? I tried to look for the file classes.txt in the repo but it seems to be missing.

tram-tram-1   | [2023-08-31 04:06:26] INFO [tram.ml.base] Processing Job #8: loki_bot-grem_gold_k0gaDC9.pdf
tram-tram-1   | [2023-08-31 04:06:41] ERROR [tram.ml.base] Failed to create report for loki_bot-grem_gold_k0gaDC9.pdf.
tram-tram-1   | Traceback (most recent call last):
tram-tram-1   |   File "/tram/src/tram/ml/base.py", line 514, in run_model
tram-tram-1   |     report = self.model.process_job(job)
tram-tram-1   |   File "/tram/src/tram/ml/base.py", line 420, in process_job
tram-tram-1   |     df = self.predict_samples(samples)
tram-tram-1   |   File "/tram/.venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
tram-tram-1   |     return func(*args, **kwargs)
tram-tram-1   |   File "/tram/src/tram/ml/base.py", line 381, in predict_samples
tram-tram-1   |     with open(settings.ML_MODEL_DIR + "/bert_model/classes.txt") as f:
**tram-tram-1   | FileNotFoundError: [Errno 2] No such file or directory: '/tram/data/ml-models/bert_model/classes.txt'**

**Comment by 0x4143** [comment]
Yes, I'm also seeing the same. Tried with three different reports, all resulting in the exact same error message referencing the missing classes.txt file.
