### ISSUE TITLE
DJANGO_DEBUG not available for running TRAM as developer.

### ISSUE THREAD

**Issue by hoangcuongnguyen2001** [center-for-threat-informed-defense/tram#196]
I am looking to run TRAM as developer to contribute to this project; however when I tried to run TRAM in localhost with DJANGO_DEBUG, my PowerShell and Anaconda could not recognize DJANGO_DEBUG as a part of my command:
![image](https://github.com/center-for-threat-informed-defense/tram/assets/76920754/590e0d8b-7628-4fc1-bb7a-2cf8c6a358dd)
I have tried to remove DJANGO_DEBUG, but it forced me to set settings for allowed hosts as well. So could you tell me what should I do to run TRAM in my local server?

**Comment by victorjomi6** [comment]
Hmm... try this:

- Install python-dotenv (with pip)
- Create a .env file in the tram folder. 
- Add: `DJANGO_DEBUG=1` in the .env file
- At the top of the settings.py file import dotenv 
- Add: dotenv.load_dotenv() on the next line.
- Then run `tram runserver` without DJANGO_DEBUG=1. 

I think this should work.
Cheers.

**Comment by mehaase** [comment]
That `DJANGO_DEBUG=1` syntax is for Bash. The goal is to set that variable in the TRAM process environment. I think in Powershell you want to do this:

```
$env:DJANGO_DEBUG = 1
tram runserver
```

**Comment by hoangcuongnguyen2001** [comment]
Thank you @mehaase for your answer, I was able to run the website in debug mode now! 
I think as you said, it would be better for me to run the program with WSL and Bash. So I just have another question, for every single time we want to run TRAM in debug mode, do we need to follow all steps, or we just need to run the Machine Learning model and then run the application server?

**Comment by mehaase** [comment]
After initial setup, you only need to do steps 11-13 to start TRAM again.
