### ISSUE TITLE
How to change loaded model?

### ISSUE THREAD

**Issue by zxcvwrs** [center-for-threat-informed-defense/tram#208]
Hello, I have been testing the tool from the web UI, and I cannot find the option to change the model that is making the predictions. The models are visible from the ML Admin site, but is there any way to change or see which model gave the results that I see in each query?

**Comment by mehaase** [comment]
The default model is BERT. It cannot be changed from the GUI but it set when TRAM starts up. If you are using the Docker deployment, you can modify `entrypoint.sh` to specify a model other than `bert`. (The `logreg` model is the 2nd best model.) See here: https://github.com/center-for-threat-informed-defense/tram/blob/main/docker/entrypoint.sh#L53

**Comment by zxcvwrs** [comment]
Thank you for the fast reply. I believe this explanation is not added in the manual for users (or maybe I have missed it), but it would be good if it were mentioned somewhere in the docs. 
Thanks in advance

**Comment by mehaase** [comment]
Yes, that is a pre-trained SciBERT model that is fine-tuned on the TRAM training data. It's trained on a larger, improved dataset than the logreg model. We created the new data set especially for our LLM research.

**Comment by zxcvwrs** [comment]
Regarding your answer, larger improved dataset consists of data used in logreg model and added 4,070 technique-labeled sentences? I have explored the [data]( https://github.com/center-for-threat-informed-defense/tram/tree/main/data) folder but did not find precise dataset used for SciBERT, is it the [attack_may_2023_merged_bootstrap_data2.json](https://github.com/center-for-threat-informed-defense/tram/blob/main/data/training/attack_may_2023_merged_bootstrap_data2.json)?

**Comment by mehaase** [comment]
If you wish to reconstruct our training process, I suggest following the [`fine_tune_single_label.ipynb`](https://github.com/center-for-threat-informed-defense/tram/blob/main/user_notebooks/fine_tune_single_label.ipynb) notebook. The training data used there is the [`single_label.json`](https://github.com/center-for-threat-informed-defense/tram/blob/main/data/tram2-data/single_label.json) file.

The TRAM 2 training data is quite different from the training data from TRAM 1. We created a new dataset using MITRE Annotation Toolkit (MAT) that is annotated at the phrase-level, and as a result the training sets are disparate. In other words, the TRAM 2 data does not include the data from TRAM 1; the LLM and the logreg models are trained on separate datasets.

**Comment by zxcvwrs** [comment]
I am sorry for reopening this issue but I want to make sure - is the data for logreg model available somewhere in this repository? I have checked the data, and since logreg model was trained on negative samples, is it correct to assume the dataset is: [negative_data.json](https://github.com/center-for-threat-informed-defense/tram/blob/main/data/training/archive/negative_data.json)

**Comment by mehaase** [comment]
Logreg is trained on `[bootstrap-training-data.json](https://github.com/center-for-threat-informed-defense/tram/blob/main/data/training/bootstrap-training-data.json)`.
