### ISSUE TITLE
Need Guidance: How can i generate config.json and pytorch_model.bin for fine tuned SciBERT?

### ISSUE THREAD

**Issue by abhishekdhiman25** [center-for-threat-informed-defense/tram#213]
Hi Reader
Greetings,

I have installed tram using developer's setup guide on my windows 10 OS.
I also performed the fine tuning using "fine_tune_multi_label.ipynb" notebook (path: tram\user_notebooks\fine_tune_multi_label.ipynb).
I know that to use this fine tuned Sci-BERT, I have to change corresponding config.json, pytorch_model.bin and classes.txt in bert_model directory (path: tram\data\ml-models\bert_model).
 I have generated classes.txt with my data. 
 I analysed config.json file in both directories scibert_multi_label_model directory (under user notebooks generated after running fine tuning notebook) and bert_model directory (path: tram\data\ml-models\bert_model), Both JSON files are similar.
Even after running fine tuning notebook with my data the config.json was not updated under scibert_multi_label_model directory.

Question: To use fine tuned Sci-BERT for report analysis, Do I need to generate config.json and pytorch model.bin separately, If Yes how to generate them. If No how these files will be updated automatically. 
Please correct me if I am wrong somewhere.

Thanks for your help in advance.

**Comment by mehaase** [comment]
I believe this is answered in #214. Please re-open if you feel that answer is insufficient.
