### ISSUE TITLE
Download original report

### ISSUE THREAD

**Issue by MarkDavidson** [center-for-threat-informed-defense/tram#43]
As a user, I want to download the original report, so that I can see the original report after it is processed.

Acceptance Criteria:

- Original report can be downloaded from dashboard

**Comment by emmanvg** [comment]
This is fixed in https://github.com/center-for-threat-informed-defense/tram/pull/152 (which is cherry picked from https://github.com/center-for-threat-informed-defense/tram/pull/129).
