### ISSUE TITLE
nltk SSL issue in Docker

### ISSUE THREAD

**Issue by alyssa-rose** [center-for-threat-informed-defense/tram#95]
**tram_1  | [nltk_data] Error loading punkt: <urlopen error [SSL:
tram_1  | [nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
tram_1  | [nltk_data]     unable to get local issuer certificate (_ssl.c:1131)>
tram_1  | [nltk_data] Error loading wordnet: <urlopen error [SSL:
tram_1  | [nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
tram_1  | [nltk_data]     unable to get local issuer certificate (_ssl.c:1131)>**

currently getting the above error when using Docker way of downloading. Permanent fix offered [here](https://stackoverflow.com/questions/38916452/nltk-download-ssl-certificate-verify-failed).

**Comment by MarkDavidson** [comment]
Hello @alyssa-rose and thank you for the report. The guidance you link to suggests disabling SSL Verification, which I am not sure is a great idea. Has this issue resolved itself on the NLTK side, or are you blocked by it?

Thank you.
-Mark
